import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
// import "react-loading-skeleton/dist/skeleton.css"
// import 'simplebar-react/dist/simplebar.css';
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CogniDoc",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <Providers>
      <body className={cn('antialiased grainy min-h-screen font-sans',inter.className)}>
        <Toaster/>
        <Navbar/>
        {children}
      </body>
      </Providers>
    </html>
  );
}
